# Generated by Django 3.2.6 on 2021-09-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemstatus',
            name='status',
            field=models.CharField(max_length=32),
        ),
    ]
